name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        ros_distro: [ kinetic, melodic ]
        ros_repo: [ main, testing ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ros_distro }}
          ROS_REPO: ${{ matrix.ros_repo }}
